firebase_config_manager.admin_settings:
  path: '/admin/config/web-services/firebase'
  defaults:
    _form: 'Drupal\firebase_config_manager\Form\FirebaseAdminForm'
    _title: 'Firebase Config Manager'
  methods: [GET, POST]
  requirements:
    _permission: 'administer site configuration'

firebase_config_manager.update_document:
  path: '/admin/firebase/update-document'
  defaults:
    _controller: 'Drupal\firebase_config_manager\Controller\FirebaseUpdateController::updateDocument'
    _title: 'Update Firestore Document'
  methods: [POST]
  requirements:
    _permission: 'manage firebase config'

firebase_config_manager.load_firestore_documents:
  path: '/admin/firebase/load-documents'
  defaults:
    _controller: 'Drupal\firebase_config_manager\Controller\FirebaseUpdateController::loadDocuments'
    _title: 'Load Firestore Documents'
  methods: [POST]
  requirements:
    _permission: 'manage firebase config'