firebase_config_manager.admin_settings:
  title: 'Firebase Manager'
  description: 'Configure Firebase Firestore and Remote Config settings.'
  route_name: firebase_config_manager.admin_settings
  parent: system.admin_config_services  
  weight: 100  