firebase_admin_styles:
  version: 1.x
  css:
    theme:
      css/firebase_admin.css: {}

firebase_editor:
  version: 1.x
  js:
    js/firebase_editor.js: {}
  dependencies:
    - core/jquery

firebase_datatables:
  version: 1.x
  js:
    js/datatables.min.js: {}
    js/firebase_datatables.js: {}
  css:
    theme:
      css/datatables.min.css: {}
  dependencies:
    - core/jquery
    - core/drupal.ajax
    - core/drupal.once